/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import java.util.*;
import database.*;

/**
 *
 * @author Axioo
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    
    private final CRUD db = new CRUD();
    private ArrayList<Menu> orders = new ArrayList<>();
    private ArrayList<Menu> food;
    private ArrayList<Menu> drink;
    
    private Menu selectedMenu; //Current selected menu
    private long totalPrice;
    private long userPayment;
    private int orderID;
    
    public MainInterface() {
        initComponents();
        createMenu();
        
        //Randomize orderID (antara 1 - 10000)
        orderID = new Random().nextInt(10000) + 1;
        tfNoTransaksi.setText(Integer.toString(orderID));
    }
    
    private void createMenu(){
        food = db.getMenuDetail("food");
        drink = db.getMenuDetail("drink");        
        //Change menu button text
        btMakanan1.setText(food.get(0).getMenuName());
        btMakanan2.setText(food.get(1).getMenuName());
        btMakanan3.setText(food.get(2).getMenuName());
        btMinuman1.setText(drink.get(0).getMenuName());
        btMinuman2.setText(drink.get(1).getMenuName());
        btMinuman3.setText(drink.get(2).getMenuName());
    }
    private void setMenuDetail(String type, int index){ 
        if(type.equals("food")){
            selectedMenu = food.get(index);
        }
        if(type.equals("drink")){
            selectedMenu = drink.get(index);
        }
        lbNamaMenu.setText(selectedMenu.getMenuName());
        tfHargaProdukSatuan.setText("Rp. " + Integer.toString(selectedMenu.getPrice()));
        spPorsiProduk.setValue(0);
        tfHargaProdukTotal.setText("Rp. 0"); 
        
        //Debug
        System.out.println(selectedMenu.toString());
    }
    private void addMenuOrder(String type){
        orders.add(selectedMenu);
        // Updating totalPrice
        tfTotalBiaya.setText(Long.toString(totalPrice));
        tfTotalBiaya1.setText(Long.toString(totalPrice));
    }
    private void changePanel(javax.swing.JPanel show, javax.swing.JPanel hide){
        hide.setVisible(false);
        show.setVisible(true);
    }
    private void updateStatusTable(ArrayList<Order> menu){
        for(int i = 0 ; i < menu.size() ; i++){
            // Nomor Baris
            tabelPesanan.setValueAt(i+1, i, 0);
            // Nama Menu
            tabelPesanan.setValueAt(menu.get(i).getMenuName(), i, 1);
            // Quantity Menu
            tabelPesanan.setValueAt(menu.get(i).getQuantity(), i, 2);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JPanel();
        btPesan = new javax.swing.JButton();
        btCekStatus = new javax.swing.JButton();
        lbHome = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        TabMenu = new javax.swing.JTabbedPane();
        ScrollPanelMakanan = new javax.swing.JScrollPane();
        MenuMakanan = new javax.swing.JPanel();
        btMakanan1 = new javax.swing.JButton();
        btMakanan2 = new javax.swing.JButton();
        btMakanan3 = new javax.swing.JButton();
        ScrollPanelMinuman = new javax.swing.JScrollPane();
        MenuMinuman = new javax.swing.JPanel();
        btMinuman1 = new javax.swing.JButton();
        btMinuman2 = new javax.swing.JButton();
        btMinuman3 = new javax.swing.JButton();
        lbDaftarMenu = new javax.swing.JLabel();
        lbNamaMenu = new javax.swing.JLabel();
        lbHargaProdukSatuan = new javax.swing.JLabel();
        tfHargaProdukSatuan = new javax.swing.JTextField();
        lbBanyakPorsi = new javax.swing.JLabel();
        spPorsiProduk = new javax.swing.JSpinner();
        lbHargaProdukTotal = new javax.swing.JLabel();
        tfTotalBiaya = new javax.swing.JTextField();
        lbTotalBiaya = new javax.swing.JLabel();
        tfHargaProdukTotal = new javax.swing.JTextField();
        btKembaliMenu = new javax.swing.JButton();
        btLanjut = new javax.swing.JButton();
        btTambahMenu = new javax.swing.JButton();
        Transaksi = new javax.swing.JPanel();
        lbPembayaran = new javax.swing.JLabel();
        lbNoTransaksi = new javax.swing.JLabel();
        tfNoTransaksi = new javax.swing.JTextField();
        lbTotalBiaya1 = new javax.swing.JLabel();
        tfTotalBiaya1 = new javax.swing.JTextField();
        lbUangAnda = new javax.swing.JLabel();
        tfInputUang = new javax.swing.JTextField();
        lbTotalKembalian = new javax.swing.JLabel();
        tfTotalKembalian = new javax.swing.JTextField();
        lbStatusPembayaran = new javax.swing.JLabel();
        btKembaliTransaksi = new javax.swing.JButton();
        btBayar = new javax.swing.JButton();
        Status = new javax.swing.JPanel();
        lbPembayaran1 = new javax.swing.JLabel();
        lbMasukanNoTransaksi = new javax.swing.JLabel();
        tfInputNoTransaksi = new javax.swing.JTextField();
        lbStatusPesanan = new javax.swing.JLabel();
        btKembaliStatus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPesanan = new javax.swing.JTable();
        btCariNoTransaksi = new javax.swing.JButton();
        lbStatusPencarian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        btPesan.setText("Pesan");
        btPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btPesanMousePressed(evt);
            }
        });

        btCekStatus.setText("Cek Status");
        btCekStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCekStatusMousePressed(evt);
            }
        });

        lbHome.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lbHome.setText("Silahkan Pilih Menu Yang Tersedia");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addComponent(lbHome)
                        .addGap(135, 135, 135))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCekStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );

        HomeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCekStatus, btPesan});

        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCekStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191))
        );

        HomeLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCekStatus, btPesan});

        Menu.setPreferredSize(new java.awt.Dimension(800, 600));

        btMakanan1.setText("Makanan 1");
        btMakanan1.setPreferredSize(new java.awt.Dimension(150, 150));
        btMakanan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMakanan1MouseClicked(evt);
            }
        });

        btMakanan2.setText("Makanan 2");
        btMakanan2.setPreferredSize(new java.awt.Dimension(150, 150));
        btMakanan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btMakanan2MousePressed(evt);
            }
        });

        btMakanan3.setText("Makanan 3");
        btMakanan3.setPreferredSize(new java.awt.Dimension(150, 150));
        btMakanan3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMakanan3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuMakananLayout = new javax.swing.GroupLayout(MenuMakanan);
        MenuMakanan.setLayout(MenuMakananLayout);
        MenuMakananLayout.setHorizontalGroup(
            MenuMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuMakananLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(MenuMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMakanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMakanan2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMakanan3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        MenuMakananLayout.setVerticalGroup(
            MenuMakananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuMakananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMakanan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMakanan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMakanan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        ScrollPanelMakanan.setViewportView(MenuMakanan);

        TabMenu.addTab("Makanan", ScrollPanelMakanan);

        btMinuman1.setText("Minuman 1");
        btMinuman1.setPreferredSize(new java.awt.Dimension(150, 150));
        btMinuman1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMinuman1MouseClicked(evt);
            }
        });

        btMinuman2.setText("Minuman 2");
        btMinuman2.setPreferredSize(new java.awt.Dimension(150, 150));
        btMinuman2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btMinuman2MousePressed(evt);
            }
        });

        btMinuman3.setText("Minuman 3");
        btMinuman3.setPreferredSize(new java.awt.Dimension(150, 150));
        btMinuman3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMinuman3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuMinumanLayout = new javax.swing.GroupLayout(MenuMinuman);
        MenuMinuman.setLayout(MenuMinumanLayout);
        MenuMinumanLayout.setHorizontalGroup(
            MenuMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuMinumanLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(MenuMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMinuman1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMinuman2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMinuman3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        MenuMinumanLayout.setVerticalGroup(
            MenuMinumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuMinumanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMinuman1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMinuman2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMinuman3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        ScrollPanelMinuman.setViewportView(MenuMinuman);

        TabMenu.addTab("Minuman", ScrollPanelMinuman);

        lbDaftarMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lbDaftarMenu.setText("Daftar Menu");

        lbNamaMenu.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lbNamaMenu.setText("Produk");

        lbHargaProdukSatuan.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbHargaProdukSatuan.setText("Harga Satuan");

        tfHargaProdukSatuan.setEditable(false);
        tfHargaProdukSatuan.setText("-- Silahkan Pilih Menu --");
        tfHargaProdukSatuan.setFocusable(false);
        tfHargaProdukSatuan.setRequestFocusEnabled(false);

        lbBanyakPorsi.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbBanyakPorsi.setText("Banyak Porsi");

        spPorsiProduk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spPorsiProduk.setFocusable(false);
        spPorsiProduk.setRequestFocusEnabled(false);
        spPorsiProduk.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spPorsiProdukStateChanged(evt);
            }
        });

        lbHargaProdukTotal.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbHargaProdukTotal.setText("Harga Total");

        tfTotalBiaya.setEditable(false);
        tfTotalBiaya.setText("Rp. 0");
        tfTotalBiaya.setFocusable(false);

        lbTotalBiaya.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbTotalBiaya.setText("Total Biaya Anda");

        tfHargaProdukTotal.setEditable(false);
        tfHargaProdukTotal.setText("-- Silahkan Pilih Menu --");
        tfHargaProdukTotal.setFocusable(false);

        btKembaliMenu.setText("Kembali");
        btKembaliMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btKembaliMenuMousePressed(evt);
            }
        });

        btLanjut.setText("Lanjut");
        btLanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btLanjutMousePressed(evt);
            }
        });

        btTambahMenu.setText("Tambah");
        btTambahMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btTambahMenuMousePressed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btKembaliMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TabMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbDaftarMenu)))
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MenuLayout.createSequentialGroup()
                                        .addComponent(lbHargaProdukSatuan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfHargaProdukSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                    .addGroup(MenuLayout.createSequentialGroup()
                                        .addComponent(lbHargaProdukTotal)
                                        .addGap(21, 21, 21)
                                        .addComponent(tfHargaProdukTotal))
                                    .addGroup(MenuLayout.createSequentialGroup()
                                        .addComponent(lbBanyakPorsi)
                                        .addGap(13, 13, 13)
                                        .addComponent(spPorsiProduk))
                                    .addComponent(tfTotalBiaya)
                                    .addComponent(lbTotalBiaya)
                                    .addGroup(MenuLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbNamaMenu))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btTambahMenu)
                                .addGap(98, 98, 98)))))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lbDaftarMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(TabMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                        .addComponent(lbNamaMenu)
                        .addGap(85, 85, 85)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHargaProdukSatuan)
                            .addComponent(tfHargaProdukSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbBanyakPorsi)
                            .addComponent(spPorsiProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHargaProdukTotal)
                            .addComponent(tfHargaProdukTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btTambahMenu)
                        .addGap(37, 37, 37)
                        .addComponent(lbTotalBiaya)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)))
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btKembaliMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLanjut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        lbPembayaran.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lbPembayaran.setText("Pembayaran");

        lbNoTransaksi.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbNoTransaksi.setText("No Transaksi");

        tfNoTransaksi.setEditable(false);
        tfNoTransaksi.setText("<< -- EMPTY -- >>");
        tfNoTransaksi.setFocusable(false);

        lbTotalBiaya1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbTotalBiaya1.setText("Total Biaya Anda");

        tfTotalBiaya1.setEditable(false);
        tfTotalBiaya1.setText("Rp. 0");
        tfTotalBiaya1.setFocusable(false);

        lbUangAnda.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbUangAnda.setText("Uang Anda");

        tfInputUang.setText("Rp. 0");
        tfInputUang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfInputUangFocusGained(evt);
            }
        });

        lbTotalKembalian.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbTotalKembalian.setText("Total Kembalian");

        tfTotalKembalian.setEditable(false);
        tfTotalKembalian.setText("Rp. 0");
        tfTotalKembalian.setFocusable(false);

        lbStatusPembayaran.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbStatusPembayaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatusPembayaran.setText("Pembayaran berhasil");

        btKembaliTransaksi.setText("Kembali");
        btKembaliTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btKembaliTransaksiMousePressed(evt);
            }
        });

        btBayar.setText("Bayar");
        btBayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btBayarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout TransaksiLayout = new javax.swing.GroupLayout(Transaksi);
        Transaksi.setLayout(TransaksiLayout);
        TransaksiLayout.setHorizontalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiLayout.createSequentialGroup()
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TransaksiLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TransaksiLayout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addComponent(lbPembayaran))
                            .addGroup(TransaksiLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTotalBiaya1)
                                    .addComponent(lbUangAnda))
                                .addGap(35, 35, 35)
                                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfInputUang, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTotalBiaya1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TransaksiLayout.createSequentialGroup()
                        .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(TransaksiLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lbNoTransaksi))
                                .addGroup(TransaksiLayout.createSequentialGroup()
                                    .addGap(262, 262, 262)
                                    .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbStatusPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btKembaliTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(TransaksiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTotalKembalian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfTotalKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );
        TransaksiLayout.setVerticalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNoTransaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalBiaya1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotalBiaya1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUangAnda)
                    .addComponent(tfInputUang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTotalKembalian))
                .addGap(18, 18, 18)
                .addComponent(btBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(lbStatusPembayaran)
                .addGap(81, 81, 81)
                .addComponent(btKembaliTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        lbPembayaran1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lbPembayaran1.setText("Cek Status Pesanan");

        lbMasukanNoTransaksi.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbMasukanNoTransaksi.setText("Masukan No Transaksi Anda");

        lbStatusPesanan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStatusPesanan.setText("Status Pesanan");

        btKembaliStatus.setText("Kembali");
        btKembaliStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btKembaliStatusMousePressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");

        tabelPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Nama Menu", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelPesanan);
        if (tabelPesanan.getColumnModel().getColumnCount() > 0) {
            tabelPesanan.getColumnModel().getColumn(0).setResizable(false);
            tabelPesanan.getColumnModel().getColumn(0).setPreferredWidth(1);
            tabelPesanan.getColumnModel().getColumn(1).setResizable(false);
            tabelPesanan.getColumnModel().getColumn(1).setPreferredWidth(500);
            tabelPesanan.getColumnModel().getColumn(2).setResizable(false);
            tabelPesanan.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        btCariNoTransaksi.setText("Search");
        btCariNoTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCariNoTransaksiMouseClicked(evt);
            }
        });

        lbStatusPencarian.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbStatusPencarian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatusPencarian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout StatusLayout = new javax.swing.GroupLayout(Status);
        Status.setLayout(StatusLayout);
        StatusLayout.setHorizontalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbPembayaran1)
                .addGap(232, 232, 232))
            .addGroup(StatusLayout.createSequentialGroup()
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatusLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbMasukanNoTransaksi)
                        .addGap(18, 18, 18)
                        .addComponent(tfInputNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StatusLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(btKembaliStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(StatusLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btCariNoTransaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(StatusLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(lbStatusPesanan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(StatusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbStatusPencarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StatusLayout.setVerticalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPembayaran1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMasukanNoTransaksi)
                    .addComponent(tfInputNoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCariNoTransaksi)
                .addGap(18, 18, 18)
                .addComponent(lbStatusPencarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(lbStatusPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btKembaliStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(15, 15, 15)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btPesanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesanMousePressed
        changePanel(Menu, Home);
    }//GEN-LAST:event_btPesanMousePressed

    private void btKembaliMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKembaliMenuMousePressed
        changePanel(Home, Menu);
    }//GEN-LAST:event_btKembaliMenuMousePressed

    private void btLanjutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLanjutMousePressed
        changePanel(Transaksi, Menu);
    }//GEN-LAST:event_btLanjutMousePressed

    private void btKembaliTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKembaliTransaksiMousePressed
        changePanel(Menu, Transaksi);
    }//GEN-LAST:event_btKembaliTransaksiMousePressed

    private void btKembaliStatusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btKembaliStatusMousePressed
        changePanel(Home, Status);
    }//GEN-LAST:event_btKembaliStatusMousePressed

    private void btCekStatusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCekStatusMousePressed
        changePanel(Status, Home);
    }//GEN-LAST:event_btCekStatusMousePressed

    private void btMakanan2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMakanan2MousePressed
        setMenuDetail("food", 1);
    }//GEN-LAST:event_btMakanan2MousePressed

    private void btMakanan3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMakanan3MouseClicked
        setMenuDetail("food", 2);
    }//GEN-LAST:event_btMakanan3MouseClicked

    private void btMakanan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMakanan1MouseClicked
        setMenuDetail("food", 0);
    }//GEN-LAST:event_btMakanan1MouseClicked

    private void spPorsiProdukStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spPorsiProdukStateChanged
        int quantity = (int)spPorsiProduk.getValue();
        if (quantity < 0){
            spPorsiProduk.setValue(0);
            quantity = 0;
        }
        if(tfHargaProdukSatuan.getText().equals("-- Silahkan Pilih Menu --")){
            return;
        }
        int satuan = Integer.parseInt(tfHargaProdukSatuan.getText().substring(4));
        tfHargaProdukTotal.setText("Rp. " + (satuan * quantity));
        selectedMenu.setQuantity(quantity);
    }//GEN-LAST:event_spPorsiProdukStateChanged

    private void btTambahMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTambahMenuMousePressed
        if(tfHargaProdukTotal.getText().equals("-- Silahkan Pilih Menu --")){
            return;
        }
        System.out.println(Integer.parseInt(tfHargaProdukTotal.getText().substring(4)));
        totalPrice += Integer.parseInt(tfHargaProdukTotal.getText().substring(4));
        tfHargaProdukTotal.setText("-- Silahkan Pilih Menu --");
        tfHargaProdukSatuan.setText("-- Silahkan Pilih Menu --");
        spPorsiProduk.setValue(0);
        addMenuOrder(selectedMenu.getType());    
    }//GEN-LAST:event_btTambahMenuMousePressed

    private void btMinuman1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMinuman1MouseClicked
        setMenuDetail("drink", 0);
    }//GEN-LAST:event_btMinuman1MouseClicked

    private void btMinuman2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMinuman2MousePressed
        setMenuDetail("drink", 1);
    }//GEN-LAST:event_btMinuman2MousePressed

    private void btMinuman3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMinuman3MouseClicked
        setMenuDetail("drink", 2);
    }//GEN-LAST:event_btMinuman3MouseClicked

    private void btBayarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBayarMousePressed
        userPayment = Long.parseLong(tfInputUang.getText());
        if (userPayment < totalPrice) {
            lbStatusPembayaran.setText("Pembayaran Gagal");
            return;
        }
        btBayar.setEnabled(false);
        lbStatusPembayaran.setText("Pembayaran Berhasil");
        long change = userPayment - totalPrice;
        tfTotalKembalian.setText("Rp. " + change);
        
        // Menambah daftar pesanan baru ke DB
        // DB untuk tabel `orders`
        db.createOrder(orderID, totalPrice);
        if (orders.isEmpty()){
            return;
        }
        for(Menu order: orders){
                db.createMenuOrder(order.getType(), orderID, order);
        }
    }//GEN-LAST:event_btBayarMousePressed

    private void tfInputUangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfInputUangFocusGained
        tfInputUang.setText("");
    }//GEN-LAST:event_tfInputUangFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Home.setVisible(true);
        Menu.setVisible(false);
        Transaksi.setVisible(false);
        Status.setVisible(false);
        totalPrice = 0;
    }//GEN-LAST:event_formComponentShown

    private void btCariNoTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCariNoTransaksiMouseClicked
        int searchID = Integer.parseInt(tfInputNoTransaksi.getText());
        ArrayList<Order> daftarPesanan = db.searchOrder(searchID);
        if (daftarPesanan.isEmpty()){
            lbStatusPencarian.setText("No Transaksi " + searchID + " Tidak Ditemukan");
            return;
        }
        lbStatusPencarian.setText("");
        updateStatusTable(daftarPesanan);
    }//GEN-LAST:event_btCariNoTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        MainInterface frame = new MainInterface();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame.setVisible(true);
                //new Customer().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuMakanan;
    private javax.swing.JPanel MenuMinuman;
    private javax.swing.JScrollPane ScrollPanelMakanan;
    private javax.swing.JScrollPane ScrollPanelMinuman;
    private javax.swing.JPanel Status;
    private javax.swing.JTabbedPane TabMenu;
    private javax.swing.JPanel Transaksi;
    private javax.swing.JButton btBayar;
    private javax.swing.JButton btCariNoTransaksi;
    private javax.swing.JButton btCekStatus;
    private javax.swing.JButton btKembaliMenu;
    private javax.swing.JButton btKembaliStatus;
    private javax.swing.JButton btKembaliTransaksi;
    private javax.swing.JButton btLanjut;
    private javax.swing.JButton btMakanan1;
    private javax.swing.JButton btMakanan2;
    private javax.swing.JButton btMakanan3;
    private javax.swing.JButton btMinuman1;
    private javax.swing.JButton btMinuman2;
    private javax.swing.JButton btMinuman3;
    private javax.swing.JButton btPesan;
    private javax.swing.JButton btTambahMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBanyakPorsi;
    private javax.swing.JLabel lbDaftarMenu;
    private javax.swing.JLabel lbHargaProdukSatuan;
    private javax.swing.JLabel lbHargaProdukTotal;
    private javax.swing.JLabel lbHome;
    private javax.swing.JLabel lbMasukanNoTransaksi;
    private javax.swing.JLabel lbNamaMenu;
    private javax.swing.JLabel lbNoTransaksi;
    private javax.swing.JLabel lbPembayaran;
    private javax.swing.JLabel lbPembayaran1;
    private javax.swing.JLabel lbStatusPembayaran;
    private javax.swing.JLabel lbStatusPencarian;
    private javax.swing.JLabel lbStatusPesanan;
    private javax.swing.JLabel lbTotalBiaya;
    private javax.swing.JLabel lbTotalBiaya1;
    private javax.swing.JLabel lbTotalKembalian;
    private javax.swing.JLabel lbUangAnda;
    private javax.swing.JSpinner spPorsiProduk;
    private javax.swing.JTable tabelPesanan;
    private javax.swing.JTextField tfHargaProdukSatuan;
    private javax.swing.JTextField tfHargaProdukTotal;
    private javax.swing.JTextField tfInputNoTransaksi;
    private javax.swing.JTextField tfInputUang;
    private javax.swing.JTextField tfNoTransaksi;
    private javax.swing.JTextField tfTotalBiaya;
    private javax.swing.JTextField tfTotalBiaya1;
    private javax.swing.JTextField tfTotalKembalian;
    // End of variables declaration//GEN-END:variables
}
